services:
  common-db:
    image: mysql:8.0
    container_name: db
    restart: always
    networks:
      - db_network
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3309:3306
    volumes:
      - ./sql-init-scripts:/docker-entrypoint-initdb.d

networks:
  db_network: