name: Docker Build & Push

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [bookstore, iam]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        working-directory: ./${{ matrix.service }}
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest
