name: Deploy to EC2

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_KEY: ${{ secrets.EC2_KEY }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  RDS_HOST: ${{ secrets.RDS_HOST }}
  RDS_USER: ${{ secrets.RDS_USER }}
  RDS_PASS: ${{ secrets.RDS_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: SSH and Deploy Containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            # Login to Docker Hub
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN

            # Pull latest images
            docker pull $DOCKER_HUB_USERNAME/bookstore:latest
            docker pull $DOCKER_HUB_USERNAME/iam:latest

            # Stop and remove old containers if exist
            docker rm -f bookstore || true
            docker rm -f iam || true

            # Run Bookstore container
            docker run -d \
              --name bookstore \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://$RDS_HOST:3306/sporty_db \
              -e SPRING_DATASOURCE_USERNAME=$RDS_USER \
              -e SPRING_DATASOURCE_PASSWORD=RDS_PASSWORD \
              -p 8080:8080 \
              $DOCKER_HUB_USERNAME/bookstore:latest

            # Run IAM container
            docker run -d \
              --name iam \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://$RDS_HOST:3306/sporty_iam \
              -e SPRING_DATASOURCE_USERNAME=$RDS_USER \
              -e SPRING_DATASOURCE_PASSWORD=RDS_PASSWORD \
              -p 8081:8080 \
              $DOCKER_HUB_USERNAME/iam:latest

            # Show running containers
            docker ps -a

          EOF