name: Deploy to EC2

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USER: ${{ secrets.EC2_USER }}
  EC2_KEY: ${{ secrets.EC2_KEY }}
  RDS_HOST: ${{ secrets.RDS_HOST }}
  RDS_PORT: 3306
  RDS_USER: ${{ secrets.RDS_USER }} 
  RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy Docker Run Script and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/bookstore:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/iam:latest

            docker stop bookstore || true
            docker rm bookstore || true
            docker stop iam || true
            docker rm iam || true

            docker run -d \
              --name bookstore \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://${RDS_HOST}:${RDS_PORT}/sporty_db \
              -e SPRING_DATASOURCE_USERNAME=${RDS_USER} \
              -e SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD} \
              -p 8080:8080 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/bookstore:latest

            docker run -d \
              --name iam \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://${RDS_HOST}:${RDS_PORT}/sporty_iam \
              -e SPRING_DATASOURCE_USERNAME=${RDS_USER} \
              -e SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD} \
              -p 8081:8080 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/iam:latest
          EOF