name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Pull latest images
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/bookstore:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/iam:latest

            # Stop and remove old containers
            docker stop bookstore || true
            docker rm bookstore || true
            docker stop iam || true
            docker rm iam || true

            # Run new containers connected to RDS
            docker run -d --name bookstore -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.RDS_HOST }}:3306/sporty_db \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.RDS_USER }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/bookstore:latest

            docker run -d --name iam -p 8081:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://${{ secrets.RDS_HOST }}:3306/sporty_iam \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.RDS_USER }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }} \
              ${{ secrets.DOCKER_HUB_USERNAME }}/iam:latest