jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'

          # Log in to Docker Hub
          echo "${DOCKER_HUB_ACCESS_TOKEN}" | docker login --username "${DOCKER_HUB_USERNAME}" --password-stdin

          # Pull latest images
          docker pull ${DOCKER_HUB_USERNAME}/bookstore:latest
          docker pull ${DOCKER_HUB_USERNAME}/iam:latest

          # Start MySQL via Docker Compose
          docker-compose -f /home/ubuntu/sportyTask/local_stack/docker-compose.yml up -d

          # Stop old microservices if exist
          docker rm -f bookstore || true
          docker rm -f iam || true

          # Run microservices
          docker run -d \
            --name bookstore \
            --env-file /home/ubuntu/sportyTask/bookstore/.env \
            -p 8080:8080 \
            ${DOCKER_HUB_USERNAME}/bookstore:latest

          docker run -d \
            --name iam \
            --env-file /home/ubuntu/sportyTask/iam/.env \
            -p 8081:8081 \
            ${DOCKER_HUB_USERNAME}/iam:latest

          EOF
