jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.RDS_PASSWORD }}
          password: ${{ secrets.RDS_PASSWORD }}

      - name: Pull and run IAM container
        run: |
          docker pull tiko1996/iam:latest
          docker stop iam || true
          docker rm iam || true
          docker run -d -p 8081:8081 \
            --name iam \
            -e DB_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            tiko1996/iam:latest

      - name: Pull and run Bookstore container
        run: |
          docker pull tiko1996/bookstore:latest
          docker stop bookstore || true
          docker rm bookstore || true
          docker run -d -p 8080:8080 \
            --name bookstore \
            -e DB_PASSWORD=${{ secrets.RDS_PASSWORD }} \
            tiko1996/bookstore:latest