name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/bookstore:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/iam:latest
            docker stop bookstore || true
            docker rm bookstore || true
            docker run -d --name bookstore -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://<RDS_HOST>:3306/sporty_db \
              -e SPRING_DATASOURCE_USERNAME=<RDS_USER> \
              -e SPRING_DATASOURCE_PASSWORD=<RDS_PASSWORD> \
              ${{ secrets.DOCKER_HUB_USERNAME }}/bookstore:latest
            docker stop iam || true
            docker rm iam || true
            docker run -d --name iam -p 8081:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://<RDS_HOST>:3306/sporty_iam \
              -e SPRING_DATASOURCE_USERNAME=<RDS_USER> \
              -e SPRING_DATASOURCE_PASSWORD=<RDS_PASSWORD> \
              ${{ secrets.DOCKER_HUB_USERNAME }}/iam:latest
