name: Docker Build and Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Bookstore
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/bookstore:latest ./bookstore
          docker push ${{ env.DOCKER_HUB_USERNAME }}/bookstore:latest

      - name: Build and Push IAM
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/iam:latest ./iam
          docker push ${{ env.DOCKER_HUB_USERNAME }}/iam:latest