name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [bookstore, iam]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Dockerfile exists
        run: |
          if [ ! -f ./${{ matrix.service }}/Dockerfile ]; then
            echo "Dockerfile missing in ./${{ matrix.service }}"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        working-directory: ./${{ matrix.service }}
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest ./{{ matrix.service }}
          docker tag ${{ env.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest ${{ env.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}
