name: Build and Push Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build bookstore JAR
      - name: Build Bookstore JAR
        run: |
          cd bookstore
          ./mvnw clean package -DskipTests

      # 4. Build IAM JAR
      - name: Build IAM JAR
        run: |
          cd iam
          ./mvnw clean package -DskipTests

      # 5. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      # 6. Build and push Bookstore Docker image
      - name: Build & Push Bookstore Docker Image
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/bookstore:latest ./bookstore
          docker push ${{ env.DOCKER_HUB_USERNAME }}/bookstore:latest

      # 7. Build and push IAM Docker image
      - name: Build & Push IAM Docker Image
        run: |
          docker build -t ${{ env.DOCKER_HUB_USERNAME }}/iam:latest ./iam
          docker push ${{ env.DOCKER_HUB_USERNAME }}/iam:latest